apiVersion: batch/v1
kind: Job
metadata:
  name: web-app-job
spec:
  template:
    spec:
      containers:
      - name: web-container
        image: busybox
        command:
        - /bin/sh
        - -c
        - echo "Job completed"
      restartPolicy: Never
