apiVersion: v1
kind: Pod
metadata:
  name: secret-env-app
spec:
  containers:
  - name: web-container
    image: nginx:latest
    env:
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: secret-key
