apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  template:
    spec:
      containers:
      - name: web-container
        image: nginx:latest
        livenessProbe:
          httpGet:
            path: /
            port: 80
