apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: web-app-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: web-container
            image: busybox
            command:
            - /bin/sh
            - -c
            - date; echo "Hello from the web app"
          restartPolicy: OnFailure
