apiVersion: v1
kind: Pod
metadata:
  name: resource-limited-app
spec:
  containers:
  - name: web-container
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
